config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :email_confirmations, only: %w[edit]
  resources :password_resets,     only: %w[new create edit update]
  resources :posts,               only: %w[create destroy]
  resources :relationships,       only: %w[create destroy]
  
  get     "help"    ,to: "static_pages#help"
  get     "about"   ,to: "static_pages#about"
  get     "contact" ,to: "static_pages#contact"
  get     "signup"  ,to: "users#new"
  get     "signin"  ,to: "sessions#new"
  post    "signin"  ,to: "sessions#create"
  delete  "signout" ,to: "sessions#destroy"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,          only: %w[edit update]
  before_action :valid_user,        only: %w[edit update]
  before_action :check_expiration,  only: %w[edit update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)

    if !@user
      flash.now[:danger] = "Email address not found"
      render :new
    elsif !@user.confirmed?
      flash[:warning] = "Please confirm your email address first"
      redirect_to root_path
    else
      @user.create_reset_digest
      UserMailer.password_reset(@user).deliver
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      flash[:danger] = "Password can't be blank."
      render "edit"
    elsif @user.update(user_params)
      sign_in(@user)
      flash[:success] = "Password has been reset"
      redirect_to @user
    else
      render "edit"
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirmes a valid user.
    def valid_user
      if !@user
        flash.now[:danger] = "Email address not found"
        render :new
      elsif !@user.confirmed?
        flash[:warning] = "Please confirm your email address first"
        redirect_to root_path
      elsif !@user.authenticated?(:reset, params[:id])
        flash[:danger] = "The link is invalid"
        redirect_to root_path
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset link has expired."
        redirect_to new_password_reset_path
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset Password")%>

<div class="container-fluid">
    <div class="rounded d-flex justify-content-center">
        <div class="col-md-4 col-sm-12 shadow-lg p-5 bg-light">
            <div class="text-center">
                <h3 class="text-primary">Reset Password</h3>
            </div>
            <%= form_with model: @user, url: password_reset_path do |form| %>

                <%= render "shared/form_errors", errors: @user.errors %>

                <%= hidden_field_tag :email, @user.email %>

                <div class="mb-3">
                    <%= form.label :password, class: "form-label" %>
                    <%= form.password_field :password, placeholder: :password, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :password_confirmation, class: "form-label" %>
                    <%= form.password_field :password_confirmation, placeholder: :password_confirmation, class: "form-control" %>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Reset Password</button>
                </div>
                <p>
                    <div class="text-center">
                        Remember the password? Please <%= link_to "Sign In", signin_path %>
                    </div>
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password")%>

<div class="container-fluid">
    <div class="rounded d-flex justify-content-center">
        <div class="col-md-4 col-sm-12 shadow-lg p-5 bg-light">
            <div class="text-center">
                <h3 class="text-primary">Forgot password</h3>
            </div>
            <%= form_with scope: :password_reset, url: password_resets_path, local: true, data: { turbo: false } do |form| %>
                <div class="mb-3 mt-3">
                    <%= form.label :email, class: "form-label" %>
                    <%= form.email_field :email, placeholder: "Enter email", class: "form-control" %>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Reset Password</button>
                </div>
                <p>
                    <div class="text-center">
                        Remember the password? Please <%= link_to "Sign In", signin_path %>
                    </div>
                </p>
            <% end %>
        </div>
    </div>
</div>