config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :email_confirmations, only: %w[edit]
  resources :password_resets,     only: %w[new create edit update]
  resources :posts,               only: %w[create destroy]
  resources :relationships,       only: %w[create destroy]
  
  get     "help"    ,to: "static_pages#help"
  get     "about"   ,to: "static_pages#about"
  get     "contact" ,to: "static_pages#contact"
  get     "signup"  ,to: "users#new"
  get     "signin"  ,to: "sessions#new"
  post    "signin"  ,to: "sessions#create"
  delete  "signout" ,to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :active_relationships, class_name:     "Relationship",
                                    foreign_key:    "follower_id",
                                    dependent:      :destroy
    has_many :following, through: :active_relationships, source: :followed

    has_many :passive_relationships, class_name:     "Relationship",
                                     foreign_key:    "followed_id",
                                     dependent:      :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    attr_accessor   :remember_token, :confirmation_token, :reset_token
    before_save     :downcase_email
    before_create   :create_confirmation_digest

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z0-9\-.]+\.[a-z]+\z/i

    validates :full_name,   presence: true,
                            length: { maximum: 71 }
    validates :nickname,    presence: true,
                            length: { maximum: 50 },
                            uniqueness: true
    validates :email,       presence: true,
                            length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: true
    has_secure_password

    validates :password,    length: { minimum: 6 }  ,allow_nil: true

    # Returns the hash digest of the given unencrypted password
    def User.digest(unencrypted_password)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(unencrypted_password, cost: cost)
    end

    # Returns URL safe base64 token
    def User.token_base64
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in presistent sessions.
    def remember
        self.remember_token = User.token_base64
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
        self.remember_token = nil
    end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = self.send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # Send a confirmation email
    def send_confirmation_email
        UserMailer.email_confirmation(self).deliver
    end

    # Confirms the email a user signed up with.
    def confirm
        self.update_attribute(:confirmed, true)
        self.update_attribute(:confirmed_at, Time.zone.now)
    end

    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.token_base64
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    # Returns a user's feed
    def feed
        following_ids_sublelect = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
        Post.where("user_id IN (#{following_ids_sublelect}) OR user_id = :user_id", user_id: id)
    end

    def follow(user)
        following << user
    end

    def unfollow(user) 
        following.delete(user)
    end

    def following?(user)
        following.include?(user)
    end

    private
        # Converts email to all lower-case
        def downcase_email
            self.email = email.downcase
        end

        # Creates and assignes the confirmation token and digest.
        def create_confirmation_digest
            self.confirmation_token = User.token_base64
            self.confirmation_digest = User.digest(confirmation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized,  only: %w[index edit update destroy following followers]
  before_action :permitted,   only: %w[edit update]
  before_action :admin_user,  only: %w[destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.email_confirmation(@user).deliver
      flash[:info] = "Please check your email #{@user.email} and follow confirmation instructions"
      redirect_to root_path
    else
      render :new, status: :bad_request
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Successfully updated"
      redirect_to @user
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    user = User.find_by(id: params[:id])

    if !user
      flash[:warning] = "User not found"
      status = :not_found
    elsif params[:confirm_delete_user] == "delete"
      user.destroy
      flash[:info] = "#{user.full_name} deleted"
      status = :ok
    else
      flash[:danger] = "Failed deleting #{user.full_name}"
      status = :bad_request
    end

    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render "show_follow"
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render "show_follow"
  end

  private
    def user_params
      params.require(:user).permit(:full_name, :nickname, :email, :password, :password_confirmation)
    end

    # Users before filters

    # Confirms the user has permissions
    def permitted
      unless current_user.id.to_s == params[:id].to_s
        flash[:danger] = "Access denied"
        redirect_to root_path
      end
    end

    # Confirms an admin user has permissions
    def admin_user
      unless current_user.admin?
        flash[:danger] = "Access denied"
        redirect_to root_path
      end
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="card" style="border-radius: 15px;">
    <div class="card-body text-center">
        <div class="mt-3 mb-4">
            <a href="<%= user_path(user) %>">
                <img src="https://i.pravatar.cc/150?img=<%= user.id %>" alt="@<%= user.nickname %>" class="rounded-circle img-fluid" width="100">
            </a>
        </div>
        <h4 class="mb-2"><%= link_to user.full_name, user_path(user) %></h4>
        <p class="text-muted mb-4">@<%= user.nickname %> <span class="mx-2">|</span> <%= user.email %></p>
        <%= render "shared/user_stats", user: user %>
    </div>
    <div class="card-footer text-center">
        <%= render "users/user_action", user: user if signed_in? %>
    </div>
</div>

app/views/users/_user_action.html.erb
<% if current_user?(user) %>
    <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-info" %>
<% elsif current_user.following?(user) %>
    <%= render "users/user_unfollow", user: user %>
<% else %>
    <%= render "users/user_follow", user: user %>
<% end %>

app/views/users/_user_follow.html.erb
<%= form_with model: current_user.active_relationships.build do |form| %>
    <%= hidden_field_tag :followed_id, user.id %>
    <%= form.submit "Follow", class: "btn btn-outline-primary" %>
<% end %>

app/views/users/_user_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete } do |form| %>
    <%= form.submit "Unollow", class: "btn btn-outline-danger" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit #{@user.full_name} profile")%>

<div class="container-fluid">
    <div class="rounded d-flex justify-content-center">
        <div class="col-md-4 col-sm-12 shadow-lg p-5 bg-light">
            <div class="text-center">
                <h3 class="text-primary">Edit <%= @user.full_name %> profile</h3>
            </div>
            <%= form_with model: @user, url: user_path(@user) do |form| %>

                <%= render "shared/form_errors", errors: @user.errors %>

                <div class="mb-3 mt-3">
                    <%= form.label :full_name, class: "form-label" %>
                    <%= form.text_field :full_name, placeholder: "What is your name?", class: "form-control" %>
                </div>
                <div class="mb-3 mt-3">
                    <%= form.label :nickname, class: "form-label" %>
                    <%= form.text_field :nickname, placeholder: "Choose your nickname", class: "form-control" %>
                </div>
                <div class="mb-3 mt-3">
                    <%= form.label :email, class: "form-label" %>
                    <%= form.email_field :email, placeholder: "Enter email", class: "form-control", disabled: true %>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users")%>

<%= will_paginate @clients, list_classes: %w(pagination justify-content-center) %>

<ul id="users" class="users">
    <% @users.each do |user| %>
        <div class="mb-4">
            <%= render user %>
        </div>
    <% end %>
</ul>

<%= will_paginate @clients, list_classes: %w(pagination justify-content-center) %>
<%= render "shared/modals/user_delete" %>
<%= javascript_include_tag "delete-user.js" %>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>

<div class="container-fluid">
    <div class="rounded d-flex justify-content-center">
        <div class="col-md-4 col-sm-12 shadow-lg p-5 bg-light">
            <div class="text-center">
                <h3 class="text-primary">Sign Up</h3>
            </div>
            <%= form_with model: @user, url: users_path(@user) do |form| %>

                <%= render "shared/form_errors", errors: @user.errors %>

                <div class="mb-3 mt-3">
                    <%= form.label :full_name, class: "form-label" %>
                    <%= form.text_field :full_name, placeholder: "What is your name?", class: "form-control" %>
                </div>
                <div class="mb-3 mt-3">
                    <%= form.label :nickname, class: "form-label" %>
                    <%= form.text_field :nickname, placeholder: "Choose your nickname", class: "form-control" %>
                </div>
                <div class="mb-3 mt-3">
                    <%= form.label :email, class: "form-label" %>
                    <%= form.email_field :email, placeholder: "Enter email", class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :password, class: "form-label" %>
                    <%= form.password_field :password, placeholder: "And password", class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :password_confirmation, class: "form-label" %>
                    <%= form.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
                <p>
                    <div class="text-center">
                        Already a member? Please <%= link_to "Sign in", signin_path %>
                    </div>
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.full_name)%>

<div id="user-profile" class="container user-profile">
    <div class="row d-flex">
        <div class="col-md-4 col-xl-4 justify-content-center align-items-center">
            <%= render @user %>
        </div>
        <% if @user.posts.any? %>
            <div class="col-md-8 col-xl-8">
                <h3>Posts (<%= @user.posts.count %>)</h3>
                <%= will_paginate @posts, list_classes: %w(pagination justify-content-start) %>
                <% @posts.each do |post| %>
                    <%= render post %>
                <% end %>
                <%= will_paginate @posts, list_classes: %w(pagination justify-content-start) %>
            </div>
        <% end %>
    </div>
</div>
<%= render "shared/modals/user_delete" %>
<%= render "shared/modals/post_delete" %>
<%= javascript_include_tag "delete-user.js" %>
<%= javascript_include_tag "delete-post.js" %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="container user-profile">
    <div class="row d-flex">
        <div class="col-md-5 col-xl-5 justify-content-center align-items-center">
            <%= render @user %>
            <div class="mt-3">
                <% if @users.any? %>
                    <% @users.each do |user| %>
                        <a href="<%= user_path(user) %>">
                            <img src="https://i.pravatar.cc/150?img=<%= user.id %>" alt="@<%= user.nickname %>" width="40">
                        </a>
                    <% end %>
                <% end %>
            </div>
        </div>
        <% if @users.any? %>
            <div class="col-md-7 col-xl-7">
                <%= will_paginate @users, list_classes: %w(pagination justify-content-start) %>
                <% @users.each do |user| %>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="card-text">
                                <img src="https://i.pravatar.cc/150?img=<%= user.id %>" alt="@<%= user.nickname %>" class="rounded-circle" width="60">
                                <%= link_to user.full_name, user_path(user) %>
                            </div>
                        </div>
                    </div>
                <% end %>
                <%= will_paginate @users, list_classes: %w(pagination justify-content-start) %>
            </div>
        <% end %>
    </div>
</div>