config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :email_confirmations, only: %w[edit]
  resources :password_resets,     only: %w[new create edit update]
  resources :posts,               only: %w[create destroy]
  resources :relationships,       only: %w[create destroy]
  
  get     "help"    ,to: "static_pages#help"
  get     "about"   ,to: "static_pages#about"
  get     "contact" ,to: "static_pages#contact"
  get     "signup"  ,to: "users#new"
  get     "signin"  ,to: "sessions#new"
  post    "signin"  ,to: "sessions#create"
  delete  "signout" ,to: "sessions#destroy"
end

app/views/shared/_form_errors.html.erb
<% if errors.any? %>
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">The form contains <%= pluralize(errors.count, "error") %>:</h4>
        <ul>
            <% errors .each do |error| %>
                <li>
                    <%= error.full_message %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with model: @post, local: true, data: { turbo: false } do |form| %>
    <%= render "shared/form_errors", errors: @post.errors %>
    <div class="mb-3">
      <%= form.text_area :content, placeholder: "Compose new post", class: "form-control", rows: "3" %>
    </div>
    <div class="mb-3">
      <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
<% end %>

app/views/shared/_user_stats.html.erb
<div class="d-flex justify-content-center text-center mb-2 user-stats">
    <a href="<%= user_path(user) %>">
        <div class="mx-2">
            <p class="mb-2 h5"><%= user.posts.count %></p>
            <p class="mb-0"><%= "post".pluralize(user.posts.count) %></p>
        </div>
    </a>
    <a href="<%= following_user_path(user) %>">
        <div class="mx-2">
            <p class="mb-2 h5"><%= user.following.count %></p>
            <p class="mb-0">following</p>
        </div>
    </a>
    <a href="<%= followers_user_path(user) %>">
        <div class="mx-2">
            <p class="mb-2 h5"><%= user.followers.count %></p>
            <p class="mb-0"><%= "follower".pluralize(user.followers.count) %></p>
        </div>
    </a>
</div>
 