config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :email_confirmations, only: %w[edit]
  resources :password_resets,     only: %w[new create edit update]
  resources :posts,               only: %w[create destroy]
  resources :relationships,       only: %w[create destroy]
  
  get     "help"    ,to: "static_pages#help"
  get     "about"   ,to: "static_pages#about"
  get     "contact" ,to: "static_pages#contact"
  get     "signup"  ,to: "users#new"
  get     "signin"  ,to: "sessions#new"
  post    "signin"  ,to: "sessions#create"
  delete  "signout" ,to: "sessions#destroy"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="text-muted">
        The <a href="https://bitbucket.org/1beat-aaron/aaron_ror_microblog/">Microblog</a>
        by <a href="https://github.com/aaronurkin/">Aaron Urkin</a>
    </div>
    <nav>
        <ul>
            <li>
                <%= link_to "About", about_path %>
            </li>
            <li>
                <%= link_to "Contact", contact_path %>
            </li>
            <li>
                <%= link_to "Help", help_path %>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "Microblog", root_path, class: "navbar-brand logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 pull-right">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <% if signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Users", users_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="currentUserDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="currentUserDropdown">
                            <li><%= link_to "Profile", user_path(current_user), class: "dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= button_to "Sign out", signout_path, method: :delete, class: "dropdown-item" %></li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign in", signin_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div class="container">
        <% flash.each do |severity, message| %>
          <div class="alert alert-<%= severity %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <div class="container">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>